library(shiny)
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(viridis)
library(sf)
library(Biostrings)
library(leaflet)
library(stringr)
library(pals)
library(plotly)
library(forcats)
library(ape)
library(ggtree)
library(treeio)
library(ggraph)

# -----------------------------
# Load data once
# -----------------------------
full_data <- read.csv("../processed_data/processed_metadata/gathered_metadata/final/PHL_metadata_matchedToSeq_2025-11-03_n794.csv", stringsAsFactors = FALSE)
full_data$Preferred_date <- lubridate::dmy(full_data$Preferred_date)

# Load simplified shapefiles 
phl_prov_simp <- readRDS("../processed_data/gis_data/phl_prov_simp.rds")
phl_region_simp <- readRDS("../processed_data/gis_data/phl_region_simp.rds")

# Load all sequences
all_seqs_fasta <- "../processed_data/processed_sequences/241025_PHL_all_n794.fasta"
fasta_seqs <- readDNAStringSet(all_seqs_fasta)

# Source your tree plotting script (make sure it has geom_tiplab with label & key = seq_name)
source("../scripts/R/plot-timetree-interactive.R")  

# -----------------------------
# Mapping of full region names to abbreviations
# -----------------------------
region_lookup <- phl_region_simp %>%
  st_drop_geometry() %>%
  distinct(ADM1_EN) %>%
  mutate(
    Region_short = str_extract(ADM1_EN, "\\((.*?)\\)") %>% str_remove_all("[()]"),
    Region_short = ifelse(is.na(Region_short),
                          case_when(
                            ADM1_EN == "Mimaropa Region" ~ "Mimaropa",
                            TRUE ~ gsub(" Region", "", ADM1_EN)
                          ),
                          Region_short)
  )

full_data <- full_data %>%
  left_join(region_lookup, by = c("Region_std" = "ADM1_EN")) %>%
  mutate(Region_short = ifelse(is.na(Region_short), Region_std, Region_short))

region_levels <- sort(unique(full_data$Region_short))
n <- length(region_levels)
region_cols <- kelly(n + 2)[-c(1,2)]
names(region_cols) <- region_levels

# -----------------------------
# UI
# -----------------------------
ui <- fluidPage(
  titlePanel("Philippines RABV Sequence Explorer"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("host_common", "Select Host:",
                  choices = c("All", sort(unique(full_data$Host_common))), selected = "All"),
      selectInput("region", "Select Region:",
                  choices = c("All", region_levels), selected = "All"),
      sliderInput("year_range", "Year Range:",
                  min = year(min(full_data$Preferred_date, na.rm = TRUE)),
                  max = year(max(full_data$Preferred_date, na.rm = TRUE)),
                  value = c(year(min(full_data$Preferred_date, na.rm = TRUE)),
                            year(max(full_data$Preferred_date, na.rm = TRUE))),
                  sep = ""),
      hr(),
      downloadButton("download_csv", "Download Filtered Metadata"),
      downloadButton("download_ids", "Download Sequence IDs"),
      downloadButton("download_fasta", "Download Filtered FASTA")
    ),
    
    mainPanel(
      tabsetPanel(
        tabPanel("Overview",
                 wellPanel(
                   style = "background-color: #f0f8ff;",
                   h3("Overview of Available Sequences"),
                   br(),
                   h4("Total Sequences Available"),
                   textOutput("total_seq"),
                   br(),
                   h4("Generated by SPEEDIER / PhD Study"),
                   textOutput("study_seq"),
                   br(),
                   h4("Publicly Available Sequences"),
                   textOutput("public_seq")
                 ),
                 hr(),
                 h3("Host distribution and temporal trends"),
                 hr(),
                 fluidRow(
                   column(width = 8, plotlyOutput("host_plot", height = "400px")),
                   column(width = 4,
                          tableOutput("host_table"))
                 ),
                 br(), hr(),
                 plotlyOutput("temporal_region_plot", height = "600px")
        ),
        
        tabPanel("Geographic Coverage",
                 h3("Geographic Distribution of Available Sequences by Administrative Divisions"),
                 br(),
                 plotlyOutput("region_plot", height = "400px"),
                 br(), hr(),
                 plotlyOutput("province_plot", height = "900px")
        ),
        
        tabPanel("Mapped Spatial Distribution of Sequences",
                 h4("By Region"),
                 leafletOutput("region_map_leaflet", height = 500),
                 br(), hr(),
                 h4("By Province"),
                 leafletOutput("province_map_leaflet", height = 500),
                 br(), hr(),
                 h4("Interactive Map Points"),
                 leafletOutput("map_points_leaflet", height = 500)
        ),
        
        tabPanel("Phylogenetic tree",
                 h3("Time-scaled phylogeny and spatial distribution of sequences"),
                 p("Select tips on the tree to update the map with corresponding sequences."),
                 fluidRow(
                   column(width = 12, plotlyOutput("timetree_plotly", height = "800px"))
                 )
        )
      )
    )
  )
)

# -----------------------------
# Server
# -----------------------------
server <- function(input, output, session) {
  
  # Reactive filtered data
  filtered_data <- reactive({
    df <- full_data
    if (input$host_common != "All") df <- df %>% filter(Host_common == input$host_common)
    if (input$region != "All") df <- df %>% filter(Region_short == input$region)
    df <- df %>%
      filter(year(Preferred_date) >= input$year_range[1],
             year(Preferred_date) <= input$year_range[2])
    df
  })
  
  # ---- Overview Tab ----
  output$total_seq <- renderText({ nrow(full_data) })
  output$study_seq <- renderText({ sum(full_data$Source %in% c("speedier", "phd"), na.rm = TRUE) })
  output$public_seq <- renderText({ sum(!full_data$Source %in% c("speedier", "phd"), na.rm = TRUE) })
  
  output$host_table <- renderTable({
    filtered_data() %>%
      tabyl(Host_common) %>%
      adorn_pct_formatting(digits = 1) %>%
      mutate(n = as.integer(n))
  })
  
  output$host_plot <- renderPlotly({
    df <- filtered_data()
    p <- ggplot(df, aes(x = Host_common, fill = Host_common)) +
      geom_bar() +
      theme_minimal() +
      labs(title = "Sequences by Host", x = "Host", y = "Count") +
      scale_fill_brewer(palette = "Set2") +
      theme(legend.position = "none")
    ggplotly(p)
  })
  
  output$temporal_region_plot <- renderPlotly({
    df <- filtered_data() %>%
      filter(!is.na(Preferred_date) & !is.na(Region_short)) %>%
      mutate(Year = year(Preferred_date)) %>%
      group_by(Year, Region_short) %>%
      summarise(n = n(), .groups = "drop") %>%
      arrange(Year)
    df$Region_short <- factor(df$Region_short, levels = region_levels)
    p <- ggplot(df, aes(x = factor(Year), y = n, fill = Region_short)) +
      geom_col() +
      scale_fill_manual(values = region_cols) +
      theme_minimal() +
      labs(title = "Sequences per Year by Region", x = "Year", y = "Count", fill = "Region") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    ggplotly(p) %>% layout(legend = list(orientation = "v", x = 1.05))
  })
  
  # -----------------------------
  # Region & Province barplots
  # -----------------------------
  output$region_plot <- renderPlotly({
    df_region <- filtered_data() %>%
      filter(!is.na(Region_short)) %>%
      group_by(Region_short) %>%
      summarise(n = n(), .groups = "drop") %>%
      arrange(n)
    df_region$Region_short <- factor(df_region$Region_short, levels = df_region$Region_short)
    p <- ggplot(df_region, aes(x = Region_short, y = n, fill = Region_short)) +
      geom_col() +
      scale_fill_manual(values = region_cols) +
      coord_flip() +
      theme_minimal(base_size = 14) +
      labs(title = "By Region", x = "Region", y = "Number of sequences", fill = "Region") +
      theme(legend.position = "none")
    ggplotly(p)
  })
  
  output$province_plot <- renderPlotly({
    df_stacked <- filtered_data() %>%
      filter(!is.na(Province_std) & !is.na(Region_short)) %>%
      group_by(Province_std, Region_short) %>%
      summarise(n = n(), .groups = "drop")
    
    province_totals <- df_stacked %>%
      group_by(Province_std) %>%
      summarise(total = sum(n), .groups = "drop") %>%
      arrange(total)
    
    df_stacked$Province_std <- factor(df_stacked$Province_std, levels = province_totals$Province_std)
    df_stacked$Region_short <- factor(df_stacked$Region_short, levels = region_levels)
    
    p <- ggplot(df_stacked, aes(x = Province_std, y = n, fill = Region_short)) +
      geom_col() +
      scale_fill_manual(values = region_cols) +
      coord_flip() +
      theme_minimal(base_size = 14) +
      labs(title = "By Province (coloured by Region)", x = "Province", y = "Number of sequences", fill = "Region") +
      theme(legend.position = "top")
    ggplotly(p)
  })
  
  # -----------------------------
  # Leaflet maps
  # -----------------------------
  output$map_points_leaflet <- renderLeaflet({
    pts <- full_data %>% filter(!is.na(Longitude) & !is.na(Latitude))
    pal_points <- colorFactor(palette = region_cols, domain = region_levels)
    leaflet(pts) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      setView(lng = 121, lat = 12, zoom = 5) %>%
      addCircleMarkers(lng = ~Longitude, lat = ~Latitude,
                       color = ~pal_points(Region_short),
                       radius = 3, fillOpacity = 0.7,
                       label = ~paste0(Sample_ID, " (", Host_type, ")")) %>%
      addLegend("bottomright", pal = pal_points, values = pts$Region_short, title = "Region")
  })
  
  # -----------------------------
  # Phylogenetic tree (interactive)
  # -----------------------------
  output$timetree_plotly <- renderPlotly({
    p <- plot_timetree_interactive(filtered_data(), region_cols) +
      geom_tiplab(aes(label = seq_name, key = seq_name))  # remove text
    
    ggplotly(p, source = "timetree_plotly") %>%
      layout(dragmode = "select") %>%
      event_register("plotly_selected") %>%
      event_register("plotly_relayout")
  })
  # -----------------------------
  # Map update when tree tips are selected
  # -----------------------------
  observe({
    sel <- event_data("plotly_selected", source = "timetree_plotly")
    pts <- filtered_data() %>% filter(!is.na(Longitude) & !is.na(Latitude))
    
    if (!is.null(sel)) {
      selected_ids <- sel$key
      pts <- pts %>% filter(Sample_ID %in% selected_ids)
    }
    
    pal_points <- colorFactor(palette = region_cols, domain = region_levels)
    
    leafletProxy("map_points_leaflet", data = pts) %>%
      clearMarkers() %>%
      addCircleMarkers(
        lng = ~Longitude, lat = ~Latitude,
        color = ~pal_points(Region_short),
        radius = 3, fillOpacity = 0.7,
        label = ~paste0(Sample_ID, " (", Host_type, ")")
      ) %>%
      clearControls() %>%
      addLegend("bottomright", pal = pal_points, values = pts$Region_short, title = "Region")
  })
  
  # -----------------------------
  # Downloads
  # -----------------------------
  output$download_csv <- downloadHandler(
    filename = function() paste0("filtered_metadata_", Sys.Date(), ".csv"),
    content = function(file) write.csv(filtered_data(), file, row.names = FALSE)
  )
  
  output$download_ids <- downloadHandler(
    filename = function() paste0("sequence_ids_", Sys.Date(), ".txt"),
    content = function(file) writeLines(filtered_data()$Sample_ID, con = file)
  )
  
  output$download_fasta <- downloadHandler(
    filename = function() paste0("filtered_sequences_", Sys.Date(), ".fasta"),
    content = function(file) {
      selected_seqs <- fasta_seqs[names(fasta_seqs) %in% filtered_data()$Sample_ID]
      writeXStringSet(selected_seqs, filepath = file)
    }
  )
  
}

# -----------------------------
# Run App
# -----------------------------
shinyApp(ui = ui, server = server)