library(pacman)
# Ensure pacman is installed
p_load(
  shiny, dplyr, ggplot2, janitor, lubridate,
  viridis, sf, leaflet, stringr, pals, plotly,
  forcats, ape, here, ggraph
)

#Install/load Bioconductor packages (and ggiraph, which is CRAN but tricky)
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

#Install Bioconductor packages safely
BiocManager::install(c("Biostrings", "ggtree", "treeio"), ask = FALSE, update = TRUE)

#if (!require("ggiraph")) install.packages("ggiraph")

# Load all
library(shiny)
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(viridis)
library(sf)
library(Biostrings)
library(leaflet)
library(stringr)
library(pals)
library(plotly)
library(forcats)
library(ape)
library(ggtree)
library(treeio)
library(ggraph)
#library(ggiraph)
# -----------------------------
# Load data once
# -----------------------------
full_data <- read.csv("processed_data/metadata/PHL_metadata_matchedToSeq_2026-01-09_n794.csv",stringsAsFactors = FALSE)
full_data$Preferred_date <- lubridate::dmy(full_data$Preferred_date)

# Load simplified shapefiles 
phl_prov_simp <- readRDS("processed_data/gis/phl_prov_simp.rds")
phl_region_simp <- readRDS("processed_data/gis/phl_region_simp.rds")

# Load all sequences
all_seqs_fasta <- "processed_data/sequences/241025_PHL_all_n794.fasta"
fasta_seqs <- readDNAStringSet(all_seqs_fasta)

# Source your tree plotting script
source("functions/plot-timetree-interactive.R")

# canonical region order from full dataset
region_levels <- sort(unique(full_data$Region_short))
n <- length(region_levels)

# palette for regions (Kelly)
region_cols <- kelly(n + 2)[-c(1,2)]
names(region_cols) <- region_levels

# -----------------------------
# UI
# -----------------------------
ui <- fluidPage(
  titlePanel("Philippines RABV Sequence Explorer"),
  sidebarLayout(
    sidebarPanel(
      selectInput("host_common", "Select Host:", choices = c("All", sort(unique(full_data$Host_common))), selected = "All"),
      selectInput("region", "Select Region:", choices = c("All", region_levels), selected = "All"),
selectInput("Major_Island", "Select Island:", choices = c("All", sort(unique(full_data$Major_Island))), selected = "All"),
      sliderInput("year_range", "Year Range:",
                  min = year(min(full_data$Preferred_date, na.rm = TRUE)),
                  max = year(max(full_data$Preferred_date, na.rm = TRUE)),
                  value = c(year(min(full_data$Preferred_date, na.rm = TRUE)),
                            year(max(full_data$Preferred_date, na.rm = TRUE))),
                  sep = ""),
 #     hr(),
 #     downloadButton("download_csv", "Download Filtered Metadata"),
 #     downloadButton("download_ids", "Download Sequence IDs"),
 #     downloadButton("download_fasta", "Download Filtered FASTA")
    ),
    
    mainPanel(
      tabsetPanel(
        tabPanel("Overview",
                 wellPanel(
                   style = "background-color: #f0f8ff;",
                   h3("Overview of Available Sequences"),
                   br(),
                   h4("Total Sequences Available"), textOutput("total_seq"),
                   br(),
                   h4("Generated by SPEEDIER / PhD Study"), textOutput("study_seq"),
                   br(),
                   h4("Publicly Available Sequences"), textOutput("public_seq")
                 ),
                 hr(),
                 h3("Host distribution and temporal trends"),
                 hr(),
                 fluidRow(
                   column(width = 8, plotlyOutput("host_plot", height = "400px")),
                   column(width = 4, tableOutput("host_table"))
                 ),
                 br(), hr(),
                 plotlyOutput("temporal_region_plot", height = "600px")
        ),
        tabPanel("Geographic Coverage",
                 h3("Geographic Distribution of Available Sequences by Administrative Divisions"),
                 br(),
                 plotlyOutput("region_plot", height = "400px"),
                 br(), hr(),
                 plotlyOutput("province_plot", height = "900px")
        ),
        tabPanel("Mapped Spatial Distribution of Sequences",
                 h4("By Region"),
                 leafletOutput("region_map_leaflet", height = 500),
                 br(), hr(),
                 h4("By Province"),
                 leafletOutput("province_map_leaflet", height = 500)
        ),
        tabPanel("Phylogenetic tree",
                 h3("Time-scaled phylogeny and spatial distribution of sequences"),
                 p("This view integrates genomic and geographic data.\n Please note that only sequences with exact coordinates are plotted on the map- representing only a proportion of the samples in the tree."),
                 selectInput("colour_by", "Colour tree tips by:",
                             choices = c("Region" = "Region_short", "Province" = "Province_std", "Municipality" = "Municipality_std", "Host" = "Host_common", "Island group" = "Major_Island", "Phylogenetic_clade" = "phylogenetic_clade","Phylogenetic_lineage" = "lineage"),
                             selected = "Region_short"),
                 fluidRow(
                   column(width = 6, leafletOutput("map_points_leaflet", height = "800px")),
                   column(width = 6, plotlyOutput("timetree_plotly", height = "800px"))
                 )
        )
      )
    )
  )
)

# -----------------------------
# Define global colour palettes (robust)
# -----------------------------
# Function that uses Kelly for ≤22, otherwise viridis
make_palette <- function(levels_vec) {
  levels_vec <- unique(levels_vec)
  n <- length(levels_vec)
  if (n <= 22) {
    cols <- pals::kelly(n + 2)[-c(1,2)]
  } else {
    cols <- viridisLite::viridis(n)
  }
  cols <- cols[1:n]
  names(cols) <- levels_vec
  cols
}

# Global factor levels
region_levels        <- sort(unique(full_data$Region_short))
province_levels      <- sort(unique(full_data$Province_std))
municipality_levels  <- sort(unique(full_data$Municipality_std))
host_levels          <- sort(unique(full_data$Host_common))
island_levels        <- sort(unique(full_data$Major_Island))
clade_levels         <- sort(unique(full_data$major_minor_clade))

# Assign palettes (named vectors)
region_cols        <- make_palette(region_levels)
province_cols      <- make_palette(province_levels)
municipality_cols  <- make_palette(municipality_levels)
host_cols          <- make_palette(host_levels)
island_cols        <- make_palette(island_levels)
clade_cols         <- make_palette(clade_levels)

# -----------------------------
# Server
# -----------------------------
server <- function(input, output, session) {
  
  # -----------------------------
  # Reactive filtered data
  # -----------------------------
  filtered_data <- reactive({
    df <- full_data
    if (input$host_common != "All") df <- df %>% filter(Host_common == input$host_common)
    if (input$region != "All") df <- df %>% filter(Region_short == input$region)
    if (input$Major_Island != "All") df <- df %>% filter(Major_Island == input$Major_Island)
    df <- df %>%
      filter(year(Preferred_date) >= input$year_range[1],
             year(Preferred_date) <= input$year_range[2])
    df
  })
  
  # -----------------------------
  # Palette generation (distinctive)
  # -----------------------------
  library(pals)
  library(RColorBrewer)
  # optional if you want randomcoloR fallback
  # library(randomcoloR)
  
  make_distinctive_palette <- function(levels_vec) {
    levels_vec <- unique(levels_vec)
    n <- length(levels_vec)
    
    if (n <= 22) {
      # Use Kelly palette for small number of levels
      cols <- pals::kelly(n + 2)[-c(1,2)]
    } else if (n <= 74) {
      # Combine qualitative RColorBrewer palettes
      qual_info <- brewer.pal.info[brewer.pal.info$category == "qual", ]
      col_vec <- unlist(
        mapply(function(ncol, pname) brewer.pal(ncol, pname),
               qual_info$maxcolors, rownames(qual_info))
      )
      # Sample without replacement to match number of levels
      if (length(col_vec) < n) {
        # fallback: extend with viridis if too few
        col_vec <- c(col_vec, viridisLite::viridis(n - length(col_vec)))
      }
      cols <- sample(col_vec, n)
    } else {
      # For very many categories, use viridis or colourRampPalette
      cols <- grDevices::colorRampPalette(viridisLite::viridis(10))(n)
      # Optionally, if randomcoloR is installed:
      # cols <- randomcoloR::distinctColorPalette(n)
    }
    
    names(cols) <- levels_vec
    cols
  }
  
  # -----------------------------
  # Shared palette reactive for app
  # -----------------------------
  palette_info <- reactive({
    colour_var <- input$colour_by
    
    # Determine factor levels & pick palette
    domain_vals <- sort(unique(full_data[[colour_var]]))
    pal_cols <- make_distinctive_palette(domain_vals)
    
    list(
      colours = pal_cols,
      domain  = domain_vals,
      var = colour_var
    )
  })
  
  # ---- Overview Tab ----
  output$total_seq <- renderText({ nrow(full_data) })
  output$study_seq <- renderText({
    sum(grepl("speedier|phd|workshop", full_data$Source, ignore.case = TRUE), na.rm = TRUE)
  })
  
  output$public_seq <- renderText({
    sum(!grepl("speedier|phd|workshop", full_data$Source, ignore.case = TRUE), na.rm = TRUE)
  })
  
  # Host summary
  output$host_table <- renderTable({
    filtered_data() %>%
      tabyl(Host_common) %>%
      adorn_pct_formatting(digits = 1) %>%
      mutate(n = as.integer(n))
  })
  
  output$host_plot <- renderPlotly({
    df <- filtered_data()
    p <- ggplot(df, aes(x = Host_common, fill = Host_common)) +
      geom_bar() +
      theme_minimal() +
      labs(title = "Sequences by Host", x = "Host", y = "Count") +
      scale_fill_brewer(palette = "Set2") +
      theme(legend.position = "none")
    ggplotly(p)
  })
  
  # Temporal plots
  output$temporal_region_plot <- renderPlotly({
    df <- filtered_data() %>%
      filter(!is.na(Preferred_date) & !is.na(Region_short)) %>%
      mutate(Year = year(Preferred_date)) %>%
      group_by(Year, Region_short) %>%
      summarise(n = n(), .groups = "drop") %>%
      arrange(Year)
    req(nrow(df) > 0)
    df$Region_short <- factor(df$Region_short, levels = region_levels)
    p <- ggplot(df, aes(x = factor(Year), y = n, fill = Region_short)) +
      geom_col() +
      scale_fill_manual(values = region_cols) +
      theme_minimal() +
      labs(title = "Sequences per Year by Region", x = "Year", y = "Count", fill = "Region") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    ggplotly(p) %>% layout(legend = list(orientation = "v", x = 1.05))
  })
  
  # Region & Province barplots
  output$region_plot <- renderPlotly({
    df_region <- filtered_data() %>%
      filter(!is.na(Region_short)) %>%
      group_by(Region_short) %>%
      summarise(n = n(), .groups = "drop") %>%
      arrange(n)
    req(nrow(df_region) > 0)
    df_region$Region_short <- factor(df_region$Region_short, levels = df_region$Region_short)
    p <- ggplot(df_region, aes(x = Region_short, y = n, fill = Region_short)) +
      geom_col() +
      scale_fill_manual(values = region_cols) +
      coord_flip() +
      theme_minimal(base_size = 14) +
      labs(title = "By Region", x = "Region", y = "Number of sequences", fill = "Region") +
      theme(legend.position = "none")
    ggplotly(p)
  })
  
  output$province_plot <- renderPlotly({
    df_stacked <- filtered_data() %>%
      filter(!is.na(Province_std) & !is.na(Region_short)) %>%
      group_by(Province_std, Region_short) %>%
      summarise(n = n(), .groups = "drop")
    req(nrow(df_stacked) > 0)
    province_totals <- df_stacked %>%
      group_by(Province_std) %>%
      summarise(total = sum(n), .groups = "drop") %>%
      arrange(total)
    df_stacked$Province_std <- factor(df_stacked$Province_std, levels = province_totals$Province_std)
    df_stacked$Region_short <- factor(df_stacked$Region_short, levels = region_levels)
    p <- ggplot(df_stacked, aes(x = Province_std, y = n, fill = Region_short)) +
      geom_col() +
      scale_fill_manual(values = region_cols) +
      coord_flip() +
      theme_minimal(base_size = 14) +
      theme(legend.position = "top") +
      labs(title = "By Province (coloured by Region)", x = "Province", y = "Number of sequences", fill = "Region")
    ggplotly(p)
  })
  # Chloropleth maps for seq counts per adm level
  
  output$region_map_leaflet <- renderLeaflet({
    df_counts <- filtered_data() %>%
      group_by(Region_std) %>%
      summarise(n = n(), .groups = "drop")
    
    # Join counts to simplified shapefile
    region_map <- phl_region_simp %>%
      left_join(df_counts, by = c("ADM1_EN" = "Region_std")) %>%
      mutate(n = ifelse(is.na(n), 0, n))
    
    pal <- colorNumeric("YlOrRd", domain = region_map$n)
    
    leaflet(region_map) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addPolygons(
        fillColor = ~pal(n),
        weight = 1,
        color = "white",
        fillOpacity = 0.7,
        label = ~paste0(ADM1_EN, ": ", n, " sequences")
      ) %>%
      addLegend("bottomright", pal = pal, values = region_map$n, title = "Number of sequences")
  })
  output$province_map_leaflet <- renderLeaflet({
    df_counts <- filtered_data() %>%
      group_by(Province_std) %>%
      summarise(n = n(), .groups = "drop")
    
    # Join counts to simplified shapefile
    prov_map <- phl_prov_simp %>%
      left_join(df_counts, by = c("ADM2_EN" = "Province_std")) %>%
      mutate(n = ifelse(is.na(n), 0, n))
    
    pal <- colorNumeric("YlOrRd", domain = prov_map$n)
    
    leaflet(prov_map) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addPolygons(
        fillColor = ~pal(n),
        weight = 0.5,
        color = "white",
        fillOpacity = 0.7,
        label = ~paste0(ADM2_EN, ": ", n, " sequences")
      ) %>%
      addLegend("bottomright", pal = pal, values = prov_map$n, title = "Number of sequences")
  })
  # -----------------------------
  # Phylogenies
  # -----------------------------
  output$timetree_plotly <- renderPlotly({
    req(input$colour_by)
    pal <- palette_info()                     # <- use palette_info() here (not palette_shared)
    # defensive: if palette empty, fall back to region_cols
    if (length(pal$colours) == 0) {
      pal$colours <- region_cols
      pal$var <- "Region_short"
    }
    plot_timetree_interactive(
      metadata = filtered_data(),
      region_palette = pal$colours,
      tree_path = NULL,
      n_tip_sample = NULL,
      colour_by = pal$var
    )
  })
  
  # -----------------------------
  # Leaflet points map (matching tree palette)
  # -----------------------------
  output$map_points_leaflet <- renderLeaflet({
    pal <- palette_info()
    df_pts <- filtered_data() %>% filter(!is.na(Longitude) & !is.na(Latitude))
    pal_fun <- colorFactor(palette = pal$colours, domain = pal$domain, na.color = "grey70")
    leaflet(df_pts) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addCircleMarkers(
        lng = ~Longitude, lat = ~Latitude,
        color = ~pal_fun(get(pal$var)),
        fillOpacity = 0.8, radius = 4,
        label = ~paste0(Sample_ID, " (", get(pal$var), ")")
      ) #%>%
    #addLegend("bottomright", pal = pal_fun, values = df_pts[[pal$var]], title = pal$var)
  })
  
  # Reactive update of points
  observe({
    pal <- palette_info()
    pts <- filtered_data() %>% filter(!is.na(Longitude) & !is.na(Latitude))
    if (nrow(pts) == 0) pts <- full_data %>% filter(!is.na(Longitude) & !is.na(Latitude))
    pal_fun <- colorFactor(palette = pal$colours, domain = pal$domain, na.color = "grey70")
    leafletProxy("map_points_leaflet", data = pts) %>%
      clearMarkers() %>%
      clearControls() %>%
      addCircleMarkers(
        lng = ~Longitude, lat = ~Latitude,
        color = ~pal_fun(get(pal$var)),
        radius = 3, fillOpacity = 0.7,
        label = ~paste0(Sample_ID, " (", Host_type, ")")
      ) #%>%
    #  addLegend("bottomright", pal = pal_fun, values = pts[[pal$var]], title = pal$var)
  })
  
  # -----------------------------
  # Downloads
  # -----------------------------
  output$download_csv <- downloadHandler(
    filename = function() paste0("filtered_metadata_", Sys.Date(), ".csv"),
    content = function(file) write.csv(filtered_data(), file, row.names = FALSE)
  )
  
  output$download_ids <- downloadHandler(
    filename = function() paste0("sequence_ids_", Sys.Date(), ".txt"),
    content = function(file) writeLines(filtered_data()$Sample_ID, con = file)
  )
  
  output$download_fasta <- downloadHandler(
    filename = function() paste0("filtered_sequences_", Sys.Date(), ".fasta"),
    content = function(file) {
      selected_seqs <- fasta_seqs[names(fasta_seqs) %in% filtered_data()$Sample_ID]
      writeXStringSet(selected_seqs, filepath = file)
    }
  )
  
}
# -----------------------------
# Run App
# -----------------------------
shinyApp(ui = ui, server = server)
