library(shiny)
library(dplyr)
library(ggplot2)
library(janitor)
library(lubridate)
library(viridis)
library(sf)
library(Biostrings)
library(leaflet)
library(stringr)
library(pals)
library(plotly)
library(forcats)

# -----------------------------
# Load data once
# -----------------------------
full_data <- read.csv("processed_data/processed_metadata/gathered_metadata/final/PHL_metadata_matchedToSeq_2025-11-03_n794.csv",
                      stringsAsFactors = FALSE)
full_data$Preferred_date <- lubridate::dmy(full_data$Preferred_date)

# Load simplified shapefiles 
phl_prov_simp <- readRDS("processed_data/gis_data/phl_prov_simp.rds")
phl_region_simp <- readRDS("processed_data/gis_data/phl_region_simp.rds")

# Load all sequences
all_seqs_fasta <- "processed_data/processed_sequences/241025_PHL_all_n794.fasta"
fasta_seqs <- readDNAStringSet(all_seqs_fasta)

# -----------------------------
# Mapping of full region names to abbreviations
# -----------------------------
region_lookup <- phl_region_simp %>%
  st_drop_geometry() %>%
  distinct(ADM1_EN) %>%
  mutate(
    Region_short = str_extract(ADM1_EN, "\\((.*?)\\)") %>% str_remove_all("[()]"),
    Region_short = ifelse(is.na(Region_short),
                          case_when(
                            ADM1_EN == "Mimaropa Region" ~ "Mimaropa",
                            TRUE ~ gsub(" Region", "", ADM1_EN)
                          ),
                          Region_short)
  )

full_data <- full_data %>%
  left_join(region_lookup, by = c("Region_std" = "ADM1_EN")) %>%
  mutate(Region_short = ifelse(is.na(Region_short), Region_std, Region_short))

# canonical region order from full dataset (useful to keep consistent ordering/palette)
region_levels <- sort(unique(full_data$Region_short))
n <- length(region_levels)

# palette for regions (Kelly)
region_cols <- kelly(n + 3)[-c(1,2,9)]
names(region_cols) <- region_levels

# -----------------------------
# UI
# -----------------------------
ui <- fluidPage(
  titlePanel("Philippines RABV Sequence Explorer"),
  sidebarLayout(
    sidebarPanel(
      selectInput("host_type", "Select Host Type:",
                  choices = c("All", sort(unique(full_data$Host_type))), selected = "All"),
      selectInput("region", "Select Region:",
                  choices = c("All", region_levels), selected = "All"),
      sliderInput("year_range", "Year Range:",
                  min = year(min(full_data$Preferred_date, na.rm = TRUE)),
                  max = year(max(full_data$Preferred_date, na.rm = TRUE)),
                  value = c(year(min(full_data$Preferred_date, na.rm = TRUE)),
                            year(max(full_data$Preferred_date, na.rm = TRUE))),
                  sep = ""),
      hr(),
      downloadButton("download_csv", "Download Filtered Metadata"),
      downloadButton("download_ids", "Download Sequence IDs"),
      downloadButton("download_fasta", "Download Filtered FASTA")
    ),
    
    mainPanel(
      tabsetPanel(
        tabPanel("Overview",
                 wellPanel(
                   h3("Overview of Available Sequences"),
                   br(),
                   h4("Total Sequences Available"),
                   textOutput("total_seq"),
                   br(),
                   h4("Generated by SPEEDIER / PhD Study"),
                   textOutput("study_seq"),
                   br(),
                   h4("Publicly Available Sequences"),
                   textOutput("public_seq")
                 )
        ),
        
        tabPanel("Host Summary",
                 plotlyOutput("host_plot"),
                 tableOutput("host_table")
        ),
        tabPanel("Temporal Coverage",
                 plotlyOutput("temporal_plot"),
                 plotlyOutput("temporal_region_plot")
        ),
        tabPanel("Geographic Coverage",
                 plotlyOutput("region_plot"),
                 plotlyOutput("province_plot"),
                 leafletOutput("map_points_leaflet", height = 500)
        ),
        tabPanel("Region Map",
                 leafletOutput("region_map_leaflet", height = 500)
        ),
        tabPanel("Province Map",
                 leafletOutput("province_map_leaflet", height = 500)
        )
      )
    )
  )
)

# -----------------------------
# Server
# -----------------------------
server <- function(input, output, session) {
  
  # Reactive filtered data
  filtered_data <- reactive({
    df <- full_data
    if (input$host_type != "All") df <- df %>% filter(Host_type == input$host_type)
    if (input$region != "All") df <- df %>% filter(Region_short == input$region)
    df <- df %>%
      filter(year(Preferred_date) >= input$year_range[1],
             year(Preferred_date) <= input$year_range[2])
    df
  })
  
  # ---- Overview Tab ----
  output$total_seq <- renderText({
    nrow(full_data)
  })
  
  output$study_seq <- renderText({
    sum(full_data$Source %in% c("speedier", "phd"), na.rm = TRUE)
  })
  
  output$public_seq <- renderText({
    sum(!full_data$Source %in% c("speedier", "phd"), na.rm = TRUE)
  })
  
  # -----------------------------
  # Host summary
  # -----------------------------
  output$host_table <- renderTable({
    filtered_data() %>% tabyl(Host_type) %>% adorn_pct_formatting(digits = 1)
  })
  
  output$host_plot <- renderPlotly({
    df <- filtered_data()
    p <- ggplot(df, aes(x = Host_type, fill = Host_type)) +
      geom_bar() +
      theme_minimal() +
      labs(title = "Sequences by Host Type", x = "Host Type", y = "Count") +
      scale_fill_brewer(palette = "Set2")
    ggplotly(p)
  })
  
  # -----------------------------
  # Temporal plots
  # -----------------------------
  output$temporal_plot <- renderPlotly({
    df <- filtered_data() %>%
      filter(!is.na(Preferred_date)) %>%
      mutate(Year = year(Preferred_date)) %>%
      group_by(Year) %>%
      summarise(n = n(), .groups = "drop") %>%
      arrange(Year)
    req(nrow(df) > 0)
    p <- ggplot(df, aes(x = factor(Year), y = n)) +
      geom_col(fill = "gray") +
      theme_minimal() +
      labs(title = "Sequences per Year", x = "Year", y = "Count") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    ggplotly(p)
  })
  
  output$temporal_region_plot <- renderPlotly({
    df <- filtered_data() %>%
      filter(!is.na(Preferred_date) & !is.na(Region_short)) %>%
      mutate(Year = year(Preferred_date)) %>%
      group_by(Year, Region_short) %>%
      summarise(n = n(), .groups = "drop") %>%
      arrange(Year)
    
    req(nrow(df) > 0)
    
    # ensure consistent palette ordering
    df$Region_short <- factor(df$Region_short, levels = region_levels)
    
    p <- ggplot(df, aes(x = factor(Year), y = n, fill = Region_short)) +
      geom_col() +
      scale_fill_manual(values = region_cols) +
      theme_minimal() +
      labs(title = "Sequences per Year by Region", x = "Year", y = "Count", fill = "Region") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    
    ggplotly(p) %>% layout(legend = list(orientation = "v", x = 1.05))
  })
  
  # -----------------------------
  # Region & Province barplots (aggregate before ordering)
  # -----------------------------
  output$region_plot <- renderPlotly({
    df_region <- filtered_data() %>%
      filter(!is.na(Region_short)) %>%
      group_by(Region_short) %>%
      summarise(n = n(), .groups = "drop") %>%
      arrange(n)   # smallest -> largest
    
    req(nrow(df_region) > 0)
    
    df_region$Region_short <- factor(df_region$Region_short, levels = df_region$Region_short)
    
    p <- ggplot(df_region, aes(x = Region_short, y = n, fill = Region_short)) +
      geom_col() +
      scale_fill_manual(values = region_cols) +
      coord_flip() +
      theme_minimal(base_size = 14) +
      labs(title = "Sequence Distribution Across Regions", x = "Region", y = "Number of sequences", fill = "Region") +
      theme(legend.position = "none")
    
    ggplotly(p)
  })
  
  output$province_plot <- renderPlotly({
    # create stacked data, then compute province totals for ordering
    df_stacked <- filtered_data() %>%
      filter(!is.na(Province_std) & !is.na(Region_short)) %>%
      group_by(Province_std, Region_short) %>%
      summarise(n = n(), .groups = "drop")
    
    req(nrow(df_stacked) > 0)
    
    province_totals <- df_stacked %>%
      group_by(Province_std) %>%
      summarise(total = sum(n), .groups = "drop") %>%
      arrange(total)   # smallest -> largest
    
    # set province factor levels from ordered totals
    df_stacked$Province_std <- factor(df_stacked$Province_std, levels = province_totals$Province_std)
    
    # ensure consistent region factor
    df_stacked$Region_short <- factor(df_stacked$Region_short, levels = region_levels)
    
    p <- ggplot(df_stacked, aes(x = Province_std, y = n, fill = Region_short)) +
      geom_col() +
      scale_fill_manual(values = region_cols) +
      coord_flip() +
      theme_minimal(base_size = 14) +
      theme(legend.position = "none") +
      labs(title = "Sequence Distribution Across Provinces", x = "Province", y = "Number of sequences")
    
    ggplotly(p)
  })
  
  # -----------------------------
  # Leaflet maps
  # -----------------------------
  # Points map coloured by region (initial render with full data)
  output$map_points_leaflet <- renderLeaflet({
    df_pts <- full_data %>% filter(!is.na(Longitude) & !is.na(Latitude))
    pal_points <- colorFactor(palette = region_cols, domain = region_levels)
    leaflet(df_pts) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      setView(lng = 121, lat = 12, zoom = 5) %>%
      addCircleMarkers(
        lng = ~Longitude, lat = ~Latitude,
        color = ~pal_points(Region_short),
        radius = 3,
        fillOpacity = 0.7,
        label = ~paste0(Sample_ID, " (", Host_type, ")")
      ) %>%
      addLegend("bottomright", pal = pal_points, values = df_pts$Region_short, title = "Region")
  })
  
  # reactive points update
  observe({
    pts <- filtered_data() %>% filter(!is.na(Longitude) & !is.na(Latitude))
    if (nrow(pts) == 0) pts <- full_data %>% filter(!is.na(Longitude) & !is.na(Latitude))
    pal_points <- colorFactor(palette = region_cols, domain = region_levels)
    leafletProxy("map_points_leaflet", data = pts) %>%
      clearMarkers() %>%
      clearControls() %>%
      addCircleMarkers(
        lng = ~Longitude, lat = ~Latitude,
        color = ~pal_points(Region_short),
        radius = 3,
        fillOpacity = 0.7,
        label = ~paste0(Sample_ID, " (", Host_type, ")")
      ) %>%
      addLegend("bottomright", pal = pal_points, values = pts$Region_short, title = "Region")
  })
  
  # Region choropleth: initial render (full) + reactive updates via observe(leafletProxy)
  output$region_map_leaflet <- renderLeaflet({
    df_region_full <- full_data %>% filter(!is.na(Region_short)) %>% group_by(Region_short) %>% summarise(n_cases = n(), .groups = "drop")
    phl_region_plot <- phl_region_simp %>%
      left_join(region_lookup %>% select(ADM1_EN, Region_short), by = "ADM1_EN") %>%
      left_join(df_region_full, by = "Region_short")
    
    vals <- phl_region_plot$n_cases
    if (all(is.na(vals))) vals <- 0
    pal <- colorNumeric(palette = "viridis", domain = vals, na.color = "grey90")
    
    leaflet(phl_region_plot) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addPolygons(fillColor = ~pal(n_cases), color = "white", weight = 1, opacity = 1, fillOpacity = 0.7,
                  highlight = highlightOptions(weight = 3, color = "#666", fillOpacity = 0.9, bringToFront = TRUE),
                  label = ~paste0(Region_short, ": ", ifelse(is.na(n_cases), 0, n_cases), " sequences")) %>%
      addLegend("bottomright", pal = pal, values = phl_region_plot$n_cases, title = "Number of Sequences") %>%
      setView(lng = 121, lat = 12, zoom = 5)
  })
  
  observe({
    df_region <- filtered_data() %>% filter(!is.na(Region_short)) %>% group_by(Region_short) %>% summarise(n_cases = n(), .groups = "drop")
    if (nrow(df_region) == 0) df_region <- full_data %>% filter(!is.na(Region_short)) %>% group_by(Region_short) %>% summarise(n_cases = n(), .groups = "drop")
    
    phl_region_plot <- phl_region_simp %>%
      left_join(region_lookup %>% select(ADM1_EN, Region_short), by = "ADM1_EN") %>%
      left_join(df_region, by = "Region_short")
    
    vals <- phl_region_plot$n_cases
    if (all(is.na(vals))) vals <- 0
    pal <- colorNumeric(palette = "viridis", domain = vals, na.color = "grey90")
    
    leafletProxy("region_map_leaflet", data = phl_region_plot) %>%
      clearShapes() %>%
      addPolygons(fillColor = ~pal(n_cases), color = "white", weight = 1, opacity = 1, fillOpacity = 0.7,
                  highlight = highlightOptions(weight = 3, color = "#666", fillOpacity = 0.9, bringToFront = TRUE),
                  label = ~paste0(Region_short, ": ", ifelse(is.na(n_cases), 0, n_cases), " sequences")) %>%
      clearControls() %>%
      addLegend("bottomright", pal = pal, values = phl_region_plot$n_cases, title = "Number of Sequences")
  })
  
  # Province choropleth: initial + reactive
  output$province_map_leaflet <- renderLeaflet({
    df_prov_full <- full_data %>% filter(!is.na(Province_std)) %>% group_by(Province_std) %>% summarise(n_cases = n(), .groups = "drop")
    phl_prov_plot <- phl_prov_simp %>% left_join(df_prov_full, by = c("ADM2_EN" = "Province_std"))
    
    vals <- phl_prov_plot$n_cases
    if (all(is.na(vals))) vals <- 0
    pal <- colorNumeric(palette = "viridis", domain = vals, na.color = "grey90")
    
    leaflet(phl_prov_plot) %>%
      addProviderTiles(providers$CartoDB.Positron) %>%
      addPolygons(fillColor = ~pal(n_cases), color = "white", weight = 0.5, opacity = 1, fillOpacity = 0.7,
                  highlight = highlightOptions(weight = 2, color = "#666", fillOpacity = 0.9, bringToFront = TRUE),
                  label = ~paste0(ADM2_EN, ": ", ifelse(is.na(n_cases), 0, n_cases), " sequences")) %>%
      addLegend("bottomright", pal = pal, values = phl_prov_plot$n_cases, title = "Number of Sequences") %>%
      setView(lng = 121, lat = 12, zoom = 5)
  })
  
  observe({
    df_prov <- filtered_data() %>% filter(!is.na(Province_std)) %>% group_by(Province_std) %>% summarise(n_cases = n(), .groups = "drop")
    if (nrow(df_prov) == 0) df_prov <- full_data %>% filter(!is.na(Province_std)) %>% group_by(Province_std) %>% summarise(n_cases = n(), .groups = "drop")
    
    phl_prov_plot <- phl_prov_simp %>% left_join(df_prov, by = c("ADM2_EN" = "Province_std"))
    
    vals <- phl_prov_plot$n_cases
    if (all(is.na(vals))) vals <- 0
    pal <- colorNumeric(palette = "viridis", domain = vals, na.color = "grey90")
    
    leafletProxy("province_map_leaflet", data = phl_prov_plot) %>%
      clearShapes() %>%
      addPolygons(fillColor = ~pal(n_cases), color = "white", weight = 0.5, opacity = 1, fillOpacity = 0.7,
                  highlight = highlightOptions(weight = 2, color = "#666", fillOpacity = 0.9, bringToFront = TRUE),
                  label = ~paste0(ADM2_EN, ": ", ifelse(is.na(n_cases), 0, n_cases), " sequences")) %>%
      clearControls() %>%
      addLegend("bottomright", pal = pal, values = phl_prov_plot$n_cases, title = "Number of Sequences")
  })
  
  # -----------------------------
  # Downloads
  # -----------------------------
  output$download_csv <- downloadHandler(
    filename = function() paste0("filtered_metadata_", Sys.Date(), ".csv"),
    content = function(file) write.csv(filtered_data(), file, row.names = FALSE)
  )
  
  output$download_ids <- downloadHandler(
    filename = function() paste0("sequence_ids_", Sys.Date(), ".txt"),
    content = function(file) writeLines(filtered_data()$Sample_ID, con = file)
  )
  
  output$download_fasta <- downloadHandler(
    filename = function() paste0("filtered_sequences_", Sys.Date(), ".fasta"),
    content = function(file) {
      selected_seqs <- fasta_seqs[names(fasta_seqs) %in% filtered_data()$Sample_ID]
      writeXStringSet(selected_seqs, filepath = file)
    }
  )
}

# -----------------------------
# Run App
# -----------------------------
shinyApp(ui = ui, server = server)